### ISSUE TITLE
Getting ##[error](intermediate value)(intermediate value)(intermediate value) is not iterable

### ISSUE THREAD

**Issue by svenstaro** [mindsers/changelog-reader-action#10]
Hey, I really like this action but sadly somehow it fails currently with my CHANGELOG.md with error:
```
  ##[error](intermediate value)(intermediate value)(intermediate value) is not iterable
```
See log here: https://github.com/svenstaro/site24x7_exporter/runs/842970939?check_suite_focus=true
My CHANGELOG.md: https://github.com/svenstaro/site24x7_exporter/blob/eca02aa02160f9c22d9145eb1bc5dfb08988b9b8/CHANGELOG.md

I believe my CHANGELOG.md is compliant to the expected format but obviously something throws the action off.

The vague output makes it fairly hard to see what the error is, sadly.

**Comment by svenstaro** [comment]
I just tested this on v1.2.0 of this Action and it works totally fine!

**Comment by mindsers** [comment]
Thank for taking the time to report this issue.

It seems to be related to the SEMVER regex that has been updated in v1.3.0. I'm looking into it currently.

**Comment by mindsers** [comment]
@svenstaro I saw you use `## [Unreleased] - ReleaseDate` as a title for your unreleased section. Can you try to remove the " - ReleaseDate" to see if it works for you? 

Since `v1.3.0` the parser tries to parse the date too and I guess it might fail to parse "ReleaseDate".

**Comment by svenstaro** [comment]
I did it the reverse way: I added ` - ReleaseDate` to your tests and it works fine which is weird. I didn't try removing it yet due to time constraints. Perhaps you could add my CHANGELOG to this repo in the test flow and see if it breaks and debug it that way? Seems to me that this would be a quicker turnaround for you while debugging this.

**Comment by mindsers** [comment]
Ok, just tried with your file. Check out the action logs:

- no modification: https://github.com/mindsers/changelog-reader-action/runs/850387930
- without the `- ReleaseDate`: https://github.com/mindsers/changelog-reader-action/runs/850464631

It is working without the fake date. I wonder if there is a use case where we need to use fake dates...

**Comment by svenstaro** [comment]
There is a use case which is that I use the ReleaseDate as a substitution marker for my automatic release tool. I imagine it's quite a common case and it doesn't really hurt to have that there. I'd like it to also work with your action as it worked before.

**Comment by mindsers** [comment]
> substitution marker for my automatic release tool

It's actually a great use case. So, I made a fix that make the action ignore the fake dates. I'll release it today I think.

**Comment by mindsers** [comment]
Fix released!! 🎉

**Comment by svenstaro** [comment]
Tested and looking good! Thanks.
