### ISSUE TITLE
Output additional params for creating releases

### ISSUE THREAD

**Issue by aroemen** [mindsers/changelog-reader-action#15]
It would be helpful if this action added additional information to the output to support the [actions/create-release](https://github.com/actions/create-release) action. Specifically properties: tag_name, release_name, prerelease, body.

**Comment by aroemen** [comment]
@mindsers I created a fork and put in a pull request for your repo here. The readme has more information on the additional property outputs. Let me know if you'd like more detail. Thanks!

**Comment by mindsers** [comment]
Left my other questions/comments on PR 😊

**Comment by mindsers** [comment]
Closed by #17
