### ISSUE TITLE
cannot run changelog-reader action

### ISSUE THREAD

**Issue by MichaRedM** [mindsers/changelog-reader-action#2]
##[warning]Failed to download action 'https://api.github.com/repos/mindsers/changelog-reader-action/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 20.663 seconds before retry.

**Comment by mindsers** [comment]
Hi! Thanks for opening this issue. 

You should try to use one of [those version tags](https://api.github.com/repos/mindsers/changelog-reader-action/tarball/v1): `v1` doesn't exist. 

I updated the `README.md` to give the right example..

**Comment by mindsers** [comment]
I close this issue. If you're problem is not solved yet, feel free to re-open it.
