### ISSUE TITLE
Does not match "unreleased" section

### ISSUE THREAD

**Issue by bjeanes** [mindsers/changelog-reader-action#4]
I am trying to create unstable releases and use the Unreleased section in a `CHANGELOG.md`.

I was hoping that instead of grepping for `##` headers that match a v1.2.3-style semantic version, that when the version was missing, this action would simply pick the first sub-header, regardless of its title.

What do you think about this? Either, supporting "Unreleased" (and similar) as valid version identifier or just taking the `versions[0]` instead of running it through `findVersionById`?

**Comment by mindsers** [comment]
It could be a good improvement of the action. 

I am thinking about the default behavior which is currently to get the last version of the file. To keep this default behavior it could be better to support "Unreleased" version. Also it'll allow project's maintener to add other second level title without the risk of finding it in the version list.

**Comment by bjeanes** [comment]
Agreed. I've worked around this for now by prefixing my unreleased heading with the _next_ version number, but this is unideal because the next version number is not always known.

```
## v0.4.0 - Unreleased
...
## v0.3.0 - 2020-05-01
...
```

**Comment by mindsers** [comment]
@bjeanes Hi! You should now be able to use "Unreleased" as version number in your `workflow.yml` file.
