### ISSUE TITLE
Link references are filtered out from version entry

### ISSUE THREAD

**Issue by xt0rted** [mindsers/changelog-reader-action#52]
I'm working on automating the release process for https://github.com/yannickcr/eslint-plugin-react and ran into an issue where the changelog format used doesn't fully work with this action.

Example version entry:

```markdown
## [7.29.1] - 2022.02.25

### Fixed

* [`jsx-key`]: prevent false "missing array key" warning ([#3215][] @ljharb)
* [`jsx-indent`]: avoid checking returns sans jsx ([#3218][] @ljharb)
* [`jsx-key`]: avoid a crash ([#3220][] @ljharb)
* version settings: avoid a crash with an invalid version ([#3219][] @ljharb)

[7.29.1]: https://github.com/yannickcr/eslint-plugin-react/compare/v7.29.0...v7.29.1
[#3220]: https://github.com/yannickcr/eslint-plugin-react/issues/3220
[#3219]: https://github.com/yannickcr/eslint-plugin-react/issues/3219
[#3218]: https://github.com/yannickcr/eslint-plugin-react/issues/3218
[#3215]: https://github.com/yannickcr/eslint-plugin-react/issues/3215
```

There's two issues due to using link references.

1. Common links are referenced at the end of the file. In this example ``[`jsx-key`]``.
2. Version specific links are referenced at the end of the section before the next version.

I worked around the first issue by pulling the common links out in another step and appending them to the release notes.

The second issue is happening because of this line https://github.com/mindsers/changelog-reader-action/blob/66d9e432ff515d3cd6a90e0d8579b454ad45720e/src/parse-entry.js#L17

What's the reason for excluding these? Would you be open to adding a new setting to skip this filter?

**Comment by xt0rted** [comment]
For now I worked around this by pulling all links out, deduping them, and appending them to the end of the release notes. This works but results in a lot of unneeded links in the release notes which then somewhat breaks the release notes section of dependabot pr https://github.com/OctoLinker/OctoLinker/pull/1510.

**Comment by mindsers** [comment]
Tried to fix it in #58. Please have a look and tell me if it solves your issue

**Comment by mindsers** [comment]
@all-contributors please add @xt0rted for bug

**Comment by xt0rted** [comment]
@mindsers sorry I missed this, I'll give it a try sometime this week and report back.

**Comment by mindsers** [comment]
Great! Thank you!

**Comment by xt0rted** [comment]
@mindsers sorry for the long response. I just tested this and it seemed to work but there wasn't a blank line between the contents and list of links that are appended to it so they rendered incorrectly.

The format I had was:

```markdown
# CHANGELOG

## Unreleased

## 0.2.0

### Added

- Link references are filtered out from version entry ([#52][])

## 0.1.0

- Blah blah blah

[#52]: https://github.com/mindsers/changelog-reader-action/issues/52
```

And this is what was added to the release notes:

```markdown

### Added

- Link references are filtered out from version entry ([#52][])
[#52]: https://github.com/mindsers/changelog-reader-action/issues/52
```

Without the extra blank line `#52` is autolinked and displays like this `[#52][]`, and the link at the bottom is also displayed.

**Comment by mindsers** [comment]
@xt0rted Hi! It should be fixed in the new release deployed this morning. Can you try it again?
