### ISSUE TITLE
Error: releasedVersions is not defined

### ISSUE THREAD

**Issue by danilogco** [mindsers/changelog-reader-action#61]
After the new release, my deployment is not getting the version entry. The actions is raising the error:
```yml
Error: releasedVersions is not defined
```

**Comment by muhammednagy** [comment]
i am having the same issue.

**Comment by mindsers** [comment]
Hi, I'm looking into it. Will let you know when I have more details to share.

**Comment by mindsers** [comment]
@danilogco Added comments to your PR (#62)

**Comment by mindsers** [comment]
I merged #62 and will soon deploy a new version
