### ISSUE TITLE
Version's sections are restricted

### ISSUE THREAD

**Issue by SwabianCoder** [mindsers/changelog-reader-action#67]
In my changelog file I already had a entry:
````
## [1.0.0-beta.0] - 2022-07-20

### Added

- Initial project files
````

When adding another entry for 1.0.0-beta.1 I end up getting this error message:
`Only 'fixed, security' sections are allowed`

So the current entries look like this:
````
## [1.0.0-beta.1] - 2022-07-24

### Added

- Interceptor adding a Bearer Token to HTTP requests with an URL matching the defined regular expression

## [1.0.0-beta.0] - 2022-07-20

### Added

- Initial project files
````

As far as I see there's no reason why I shouldn't be able to have an `added` section for my new version as well.

**Comment by mindsers** [comment]
@SwabianCoder Thanks for taking the time to open this issue to find solution. We'll need time to think about this and understand how the community uses prerelease versions. If you have documentations to share about the topic, do not hesitate to paste them in this discussion feed.

**Comment by SwabianCoder** [comment]
@mindsers I just checked the sample changelog on [Keep a Changelog](keepachangelog.com) website. All versions listed there could e.g. have an added section.

**Comment by SwabianCoder** [comment]
@mindsers E.g.:
````
validate_sections: true | false
Default: true
````

**Comment by mindsers** [comment]
> I just checked the sample changelog on [Keep a Changelog](https://keepachangelog.com/) website. All versions listed there could e.g. have an added section.
> 
> After seeing the sample changelog on their website I was a bit wondering why your having this [has-correct-sections.js file](https://github.com/mindsers/changelog-reader-action/blob/master/src/rules/has-correct-sections.js) in your repository.

We do not have it because of Keep a Changelog but because of Semver:
<img width="741" alt="Capture d’écran 2022-08-09 à 8 33 33 AM" src="https://user-images.githubusercontent.com/3090112/183565046-76d884c3-220d-486f-a60c-0e128915bfab.png">

**Comment by SwabianCoder** [comment]
@mindsers  Then may the prerelease section restriction should be removed because SemVer docs don't really tell how to use prereleases.

**Comment by mindsers** [comment]
After looking at how the semver package works : 

> diff(v1, v2): Returns difference between two versions by the release type (major, premajor, minor, preminor, patch, prepatch, or prerelease), or null if the versions are the same.

It seems that the generic “prerelease” is returned only when two prerelease versions of the same version are compared. This remove the information about “what type of prerelease” are compared (prepatch, preminor, premajor). 

The action's code currently acts as a prerelease is always a prepatch, which is wrong and leads to this false positive in the check. Until I found a better and more accurate solution, I propose to treat the prerelease as a premajor which is the less restrictive check.

**Comment by mindsers** [comment]
@all-contributors please add @SwabianCoder  for bug

**Comment by SwabianCoder** [comment]
@mindsers Thanks for fixing this behavior! When do you release a new version containing this bugfix? I'm currently a bit blocked with further development of my open source projects due to this bug.

**Comment by mindsers** [comment]
Hi @SwabianCoder, it should be deployed and ready now.
