### ISSUE TITLE
`set-output` command deprecation

### ISSUE THREAD

**Issue by Conchylicultor** [mindsers/changelog-reader-action#77]
As reported by some users in https://github.com/mindsers/changelog-reader-action/issues/75, the `set-output` warning have not been fixed with the 2.2.1 version:

https://github.com/mindsers/changelog-reader-action/blob/master/dist/index.js#L2878

See https://github.com/mindsers/changelog-reader-action/issues/75#issuecomment-1315324350 for fix

**Comment by mindsers** [comment]
Thanks for the issue! Let's keep the conversation in #75 ;)
