### ISSUE TITLE
The reader not fully support semantic versioning (https://semver.org/)

### ISSUE THREAD

**Issue by HardNorth** [mindsers/changelog-reader-action#8]
Hello there!
First of all, thank you for the great tool! We integrated it into our pipelines for several of our projects and it works well in most cases, but not in all of the cases.

It looks like the tool only supports simple cases of versioning (MAJOR.MINOR.PATCH format), but ignores entities in CHANGELOG.md which contains pre-release and/or build metadata information.

Well, I understand it might be up to the author which version standard to support but it looks like "semver" is well-documented and therefore wide-spread. 
E.G:
NodeJS: https://github.com/conventional-changelog/standard-version

Your can check out for the details, documentation and test cases on: https://semver.org/

Thanks!

**Comment by mindsers** [comment]
Hi! Thank for taking time to report this issue! ❤️ 

The project should support SEMVER correctly and it is only a matter of regexes. I think we should try to use the one from the [semver website](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string).

You should see you version number in the following usage example : https://regex101.com/r/vkijKf/1/

**Comment by HardNorth** [comment]
Well, I can provide a TC which is not working for us: `5.0.19-TESTNG6-BETA4-SNAPSHOT`.

**Comment by mindsers** [comment]
`5.0.19-TESTNG6-BETA4` and `5.0.19-BETA-4` should be correctly handled in the next version.

**Comment by mindsers** [comment]
Hi! I wanted to let you know that the last `v1` (`v1.3.0`) has been released with the fix of the SEMVER pattern. 🎉 

If you use `changeling-reader-action@v1` your workflows should work without any further actions on your part. If not you have to update the tag you use.

Thanks for using Changelog Reader!
