### ISSUE TITLE
Update node version to node16 or higher

### ISSUE THREAD

**Issue by danilogco** [mindsers/changelog-reader-action#80]
The current used node verion is deprecated to use with Gh. Seems like there is no option to keep usng node12.

> The following actions uses node12 which is deprecated and will be forced to run on node16: mindsers/changelog-reader-action@v2.2.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by mindsers** [comment]
Should be good now. v2.2.3 uses node v20 thanks to #81

**Comment by mindsers** [comment]
@all-contributors Let's add @danilogco for bugs.
